In [1]:
#problem1
l1=[int(x) for x in input().split()]
l2=[int(x) for x in input().split()]
a11=0;a00=0;a10=0;a01=0;
for i in  range(len(l1)):
    if(l1[i]==0 and l2[i]==0):
        a00+=1
    if(l1[i]==0 and l2[i]==1):
        a01+=1
    if(l1[i]==1 and l2[i]==0):
        a10+=1
    if(l1[i]==1 and l2[i]==1):
        a11+=1
smc=0.0;jc=0.0;
smc=(a11+a00)/(a11+a10+a01+a00)
jc=(a11)/(a11+a10+a01)
print(smc)
print(jc)

1 0 0 1
0 1 0 1
0.5
0.3333333333333333


In [9]:
#problem2
import numpy as np
l=[];count=0;l1=[];count1=0;
s=input()
s1=input()
s1=s.split()
s=s.split()
for i in s:
    l.append(i.split(','))
for i in range(len(l)):
    for j in range(len(l[i])):
        l[i][j]=int(l[i][j])
        count+=1
for i in s1:
    l1.append(i.split(','))
for i in range(len(l1)):
    for j in range(len(l1[i])):
        l1[i][j]=int(l1[i][j])
        count1+=1
a=np.zeros(shape=(9,9))
s=0;t=0;y=len(l);y1=len(l1);x=0
for i in range(0,9):
    x=i
    for j in range(x+1,9):
        if i==j:
            pass
        s,t=i,j
        for k in range(0,y):
            if s in l1[k] and t in l1[k]:
                a[i,j]=1
            else:
                a[i,j]=0
print(a)

1,3,4,5 2,6 7 8,9
1,2,3,4 5,6 7,8,9
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
#problem3 
import math
def ncr(n,r):
    f=math.factorial
    return f(n)//f(r)//f(n-r)
N=int(input("enter count of p"))
l=[]
n=int(input("enter n value"))
r=int(input("enter r value"))
for i in range(N):
    p=float(input("enter p value"))
    q=1-p
    l.append(ncr(n,r)*(p**(r))*(q**(n-r)))

print("maximum likelyhood:",max(l))    

In [13]:
import math
def ncr(n,r):
    f=math.factorial
    return f(n)//f(r)//f(n-r)
n=int(input("enter n value"))
r=int(input("enter r value"))
l=lambda n,r,p:ncr(n,r)*(p**(r))*((1-p)**(n-r))
l

enter n value10
enter r value6


<function __main__.<lambda>>

In [ ]:
s=0;t=0;y=len(l);y1=len(l1)
for i in range(1,10):
    for j in range(1,10):
        if i==j:
            pass
        if i<j:
            s,t=i,j
            for k in range(0,y):
                if s in l[k] and t in l[k]:
                    a[i,j]=1
                else:
                    a[i,j]=0
        if i>j:
            s,t=i,j
            for k in range(0,y1):
                if s in l1[k] and t in l1[k]:
                    a[i,j]=1
                else:
                    a[i,j]=0
                    print(a)
      